# Generated by Django 6.0.6 on 2026-06-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('primary_color', models.CharField(default='#22C55E', help_text='Formato HEX, ej: #22C55E', max_length=7)),
                ('secondary_color', models.CharField(default='#16A34A', help_text='Formato HEX', max_length=7)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='JSON con enlaces a redes sociales')),
                ('welcome_message', models.TextField(blank=True, verbose_name='Mensaje de bienvenida')),
            ],
        ),
    ]
