# Generated by Django 6.0.6 on 2026-06-30 12:56

import django.db.models.deletion
import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], max_length=20)),
                ('voucher', models.FileField(blank=True, null=True, upload_to=payments.models.voucher_upload_path)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente de verificación'), ('verificado', 'Verificado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
        ),
    ]
