# Generated by Django 5.2.15 on 2026-06-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ocr_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto detectado en comprobante', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ocr_date',
            field=models.CharField(blank=True, help_text='Fecha detectada en comprobante', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='ocr_dni',
            field=models.CharField(blank=True, help_text='DNI o CUIL detectado', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='ocr_name',
            field=models.CharField(blank=True, help_text='Nombre del titular del comprobante', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='ocr_operation_id',
            field=models.CharField(blank=True, help_text='Nro de operación detectado', max_length=50),
        ),
    ]
