# Generated by Django 6.0.6 on 2026-06-30 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_ocr_amount_payment_ocr_date_payment_ocr_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciliation_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciliation_status',
            field=models.CharField(choices=[('conciliado', 'Conciliado'), ('monto_diferente', 'Monto diferente'), ('duplicado', 'Posible duplicado'), ('sin_datos', 'Datos insuficientes'), ('manual', 'Control manual')], db_index=True, default='sin_datos', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='voucher_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
    ]
